### PR TITLE
fix: fix generated types to missing import

### LINKED ISSUE #85: Typing issue in v7.0.0
I got this typing issue `Cannot find name ShardImport` in v7.0.0 (not happen with v6.0.0)

Screen Shot 2022-01-27 at 10 52 19

### PR DESCRIPTION
**Pull request by tuyennhv**
**Motivation**
Got this error when using this in lodestar

```
@chainsafe/lodestar: $ tsc -p tsconfig.build.json
@chainsafe/lodestar: ../../node_modules/datastore-core/types/src/index.d.ts:20:23 - error TS2304: Cannot find name 'ShardImport'.
@chainsafe/lodestar: 20     ShardBase: typeof ShardImport.ShardBase;
@chainsafe/lodestar:                          ~~~~~~~~~~~
@chainsafe/lodestar: ../../node_modules/datastore-core/types/src/index.d.ts:21:20 - error TS2304: Cannot find name 'ShardImport'.
@chainsafe/lodestar: 21     Prefix: typeof ShardImport.Prefix;
@chainsafe/lodestar:                       ~~~~~~~~~~~
@chainsafe/lodestar: ../../node_modules/datastore-core/types/src/index.d.ts:22:20 - error TS2304: Cannot find name 'ShardImport'.
@chainsafe/lodestar: 22     Suffix: typeof ShardImport.Suffix;
@chainsafe/lodestar:                       ~~~~~~~~~~~
@chainsafe/lodestar: ../../node_modules/datastore-core/types/src/index.d.ts:23:24 - error TS2304: Cannot find name 'ShardImport'.
@chainsafe/lodestar: 23     NextToLast: typeof ShardImport.NextToLast;
@chainsafe/lodestar:                           ~~~~~~~~~~~
@chainsafe/lodestar: Found 4 errors.
@chainsafe/lodestar: error Command failed with exit code 2.
```

**Description**
+ change the way to generate shard types
+ close #85

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -13,9 +12,7 @@ export const Errors = {
   ...ErrorsImport
 }
 
-export const shard = {
-  ...ShardImport
-}
+export * as shard from './shard.js';
```
Comment (achingbrain) [inline src/index.js:15]:
```suggestion
export * as shard from './shard.js'
```

**Comment by achingbrain** [comment]
I think this breaks the transpiled CJS version as it changes the shape of the exported object:

```js
// src/index.js
import * as ShardImport from './shard.js'

export const shard = {
  ...ShardImport
}
```

```js
// dist/cjs/index.js
var shard$1 = require('./shard.js');
const shard = shard$1;

exports.shard = shard;
```

vs

```js
// src/index.js
export * as shard from './shard.js'
```

```js
// dist/cjs/index.js
var shard$1 = require('./shard.js');
const shard = shard$1;

exports.PREFIX = shard.PREFIX;
exports.Prefix = shard.Prefix;
exports.README_FN = shard.README_FN;
exports.SHARDING_FN = shard.SHARDING_FN;
exports.ShardBase = shard.ShardBase;
exports.Suffix = shard.Suffix;
exports.parseShardFun = shard.parseShardFun;
exports.readShardFun = shard.readShardFun;
```

If I change `/src/index.js` to:

```js
export const Errors = ErrorsImport
export const shard = ShardImport
```

I get:

```ts
export { BaseDatastore } from "./base.js";
export { MemoryDatastore } from "./memory.js";
export { KeyTransformDatastore } from "./keytransform.js";
export { ShardingDatastore } from "./sharding.js";
export { MountDatastore } from "./mount.js";
export { TieredDatastore } from "./tiered.js";
export { NamespaceDatastore } from "./namespace.js";
export const Errors: typeof ErrorsImport;
export const shard: typeof ShardImport;
export type Shard = import("./types").Shard;
export type KeyTransform = import("./types").KeyTransform;
import * as ErrorsImport from "./errors.js";
import * as ShardImport from "./shard.js";
//# sourceMappingURL=index.d.ts.map
```

Can you try overwriting the generated `index.d.ts` with the above locally and see if it fixes the problem?

**Comment by tuyennhv** [comment]
Thanks @achingbrain for the detail, it works great!

**Review by achingbrain — APPROVED** [review]
